import Head from 'next/head'
import { BannerSection, Services } from '../components'

export default function Home() {
    return (
        <>
            <Head>
                <title>Mern Dev || Riad</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <BannerSection />
            <Services />
        </>
    )
}
